spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/security}
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:12345}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

endpoint:
  confirmUser: http://localhost:${server.port}/user/confirm

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0
jwt:
  timeout: 86400000
  secretKey: c92a0ed7d50b0146d9dd064ffffc49b1945c8d9d236841e837bb5e4ebc08f3a1
  expiryDay: 7
  refreshKey: 1e34c845918564fa8b0559a3d32182e2bee5e41a466e1e636f795eaa97c1ed7c
  resetKey: 7f3c1b0e8a4f26d9c7e9f2d11a50384b62c1e77d9452fae8cb38d40a19f06b52
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1ms
  timeout: 60000ms